---

# Git settings.
setup_git_repo: yes
git_branch: master


# Database settings.
db_user: "{{ application_name }}"
db_name: "{{ application_name }}"
db_password: password
db_host: "{{ hostvars[groups['altvr-db'][0]].ansible_eth1.ipv4.address }}"


# Gunicorn settings. For the number of workers, a good rule to follow is
# 2 x number of CPUs + 1
gunicorn_num_workers: 3

# Setting this to 1 will restart the Gunicorn process each time
# you make a request, basically reloading the code. Very handy
# when developing. Set to 0 for unlimited requests (default).
gunicorn_max_requests: 0

gunicorn_timeout_seconds: 300


# Nginx settings.
nginx_server_name: "{{ hostvars[groups['altvr-web'][0]].ansible_eth0.ipv4.address }}"
ssl_dest_dir: /etc/ssl


# Application settings.
django_settings_file: "{{ application_name }}.settings"

django_secret_key: "akr2icmg1n8%z^3fe3c+)5d0(t^cy-2_25rrl35a7@!scna^1#"

run_django_syncdb: yes
run_django_db_migrations: no
run_django_collectstatic: yes

# Datadog
datadog_enabled: yes
datadog_api_key: "{{ lookup('env', 'DD_API_KEY') }}"
datadog_postgres_password: inW9IQc2Y6xuaSOTLpeITxqr
