---

- include: datadog.yml
  when: datadog_enabled
  tags: monitoring

- include: create_swap_file.yml
  when: create_swap_file
  tags: swap

- name: Ensure bash, OpenSSL, and libssl are the latest versions
  apt: name={{ item }} update_cache={{ update_apt_cache }} state=latest
  with_items:
    - bash
    - openssl
    - libssl-dev
    - libssl-doc
  tags: packages

- name: Install base packages
  apt: name={{ item }} update_cache={{ update_apt_cache }} force=yes state=installed
  with_items:
    - python-software-properties
    - build-essential
    - acl
    - ntp
    - htop
    - git
    - libpq-dev
    - python-dev
    - python-pip
    - python-pycurl
    - supervisor
  tags: packages

- name: Add PPA for Python 2.7.10 
  apt_repository: repo=ppa:fkrull/deadsnakes-python2.7 update_cache=yes

- name: Upgrade pip
  pip: name=pip state=latest
  tags: packages

- name: Upgrade python
  apt: name=python2.7 state=latest
  tags: packages
